version: '2'

services:
  apache:
    image: nakkumar/jenkins-website-test:v3.0
    restart: always
    container_name: apache
    hostname: testing.com
    privileged: true
    command: service apache2 start
    entrypoint: bash /root/entrypoint.sh      
    ports:
      - "9001:22"
      - "9000:80"
    tty: true

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.0.0/16
         gateway: 192.168.0.1